window.cards = [
  {
    id: "UNR-001",
    name: "山田リョウ",
    category: "SPカード",
    series: "UNOREIYA SPECIAL",
    modes: ["スタンダード"],
    color: "赤",
    rarity: "ウルトラレア",
    effectShort: "強力な効果を持つ特殊カード。状況を大きく変えることができる。",
    effectFull: "強力な効果を持つ特殊カード。状況を大きく変えることができる。発動タイミングを見極めて有利を作ろう。",
    tags: ["SP", "強カード", "ぼっち・ざ・ろっく"],
    image: "images/sp001.png",
    limit: "通常",
    note: "初期デッキに組み込みやすい汎用型カード。"
  },
  {
    id: "UNR-002",
    name: "五条悟",
    category: "キャラクターカード",
    series: "呪術廻戦コレクション",
    modes: ["ブースト"],
    color: "青",
    rarity: "スーパーレア",
    effectShort: "相手の行動を制限する効果を持つ。",
    effectFull: "相手の行動を制限する効果を持つ。相手ターン中の発動を狙うと優位に立てる。",
    tags: ["妨害", "呪術廻戦"],
    image: "https://via.placeholder.com/200x300?text=五条悟",
    limit: "通常",
    note: "ターン制御に特化したカード。"
  },
  {
    id: "UNR-003",
    name: "初音ミク",
    category: "High Class",
    series: "ミュージックドリーム",
    modes: ["スタンダード"],
    color: "緑",
    rarity: "ハイレア",
    effectShort: "特定条件で追加効果を発動できる。",
    effectFull: "特定条件で追加効果を発動できる。コンボ構築が得意なプレイヤーに向くカード。",
    tags: ["High Class", "特殊効果"],
    image: "https://via.placeholder.com/200x300?text=初音ミク",
    limit: "通常",
    note: "コンボ軸のデッキに向いた一枚。"
  },
  {
    id: "UNR-004",
    name: "セイカ・エレナ",
    category: "キャラクターカード",
    series: "ネオ・アドベンチャー",
    modes: ["ブースト", "スタンダード"],
    color: "黄",
    rarity: "レア",
    effectShort: "味方全体の攻撃力を少し上げる。",
    effectFull: "このカードがフィールドにいる間、あなたの全てのキャラクターカードの攻撃力が上昇する。コンボの土台として使えるサポート性能を持つ。",
    tags: ["サポート", "強化", "冒険"],
    image: "https://via.placeholder.com/200x300?text=セイカ%E3%83%BB%E3%82%A8%E3%83%AC%E3%83%8A",
    limit: "通常",
    note: "複数デッキのサポート役として優秀。"
  },
  {
    id: "UNR-005",
    name: "テストカード",
    category: "キャラクターカード",
    series: "テストシリーズ",
    modes: ["スタンダード"],
    color: "紫",
    rarity: "ノーマル",
    effectShort: "テスト用の効果文。",
    effectFull: "これはテスト用のカードです。実際の効果は後で変更してください。",
    tags: ["テスト"],
    image: "https://via.placeholder.com/200x300?text=テストカード",
    limit: "通常",
    note: "テスト用カードです。"
  },
  {
    id: "koko",
    name: "じっけん",
    effectName: "すべる",
    effectFull: "すべりまくる",
    effectShort: "すべりまくる",
    series: "",
    category: "",
    tags: [],
    keywords: [],
    type: "",
    image: ""
  }
  
];
